name: HideAndSeek
main: net.tylermurphy.hideAndSeek.Main
version: 1.1.2
author: KenshinEto
load: STARTUP
api-version: 1.17
depend: [ProtocolLib]
commands:
  hideandseek:
    description: Hide and Seek command
    usage: /hideandseek [about|help|start|stop|setspawn|setseeker]
    permission: hideAndSeek.admin
    aliases: hs